spring:
  datasource:
    url: jdbc:mysql://209.250.235.48:3306/teachassistant
    username: wxz
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/templates
  mvc:
    view:
      suffix: .html

