spring:
  datasource:
    url: jdbc:mysql://209.250.235.48:3306/teachassistant
    username: jxr
    password: jxr19981101
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/
  mvc:
    view:
      suffix: .html
